# Generated by Django 5.2.17 on 2026-09-27 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import community.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_alter_event_shrinkage_lambda'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=community.models._flag_id, max_length=32, unique=True)),
                ('kind', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=64)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_flags', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=community.models._voter_id, max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('user', 'User'), ('email', 'Email'), ('device', 'Device')], max_length=8)),
                ('email_hash', models.CharField(blank=True, max_length=64)),
                ('device_hash', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_voters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=community.models._ballot_id, max_length=32, unique=True)),
                ('order_seed', models.CharField(default=community.models._order_seed, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ballot', to='community.voter')),
            ],
        ),
        migrations.CreateModel(
            name='VotingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('open_link', 'Open link'), ('email', 'Email verification'), ('authenticated', 'Authenticated account')], default='open_link', max_length=16)),
                ('style', models.CharField(choices=[('single', 'Single vote'), ('quadratic', 'Quadratic')], default='single', max_length=16)),
                ('credits', models.PositiveIntegerField(default=16)),
                ('max_votes_per_project', models.PositiveIntegerField(default=1)),
                ('link_token', models.CharField(default=community.models._new_link_token, max_length=64, unique=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_config', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='BallotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='community.ballot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_ballot_items', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ballot', 'project'), name='community_ballot_project_uniq'), models.CheckConstraint(condition=models.Q(('votes__gte', 0)), name='community_ballot_votes_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=community.models._comment_id, max_length=32, unique=True)),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hide_reason', models.CharField(blank=True, max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_comments_hidden', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='projects.project')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['project', 'hidden_at', 'created_at'], name='community_comment_visible_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['event', 'ip_hash', 'created_at'], name='community_voter_ip_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='community_voter_event_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(condition=models.Q(('email_hash', ''), _negated=True), fields=('event', 'email_hash'), name='community_voter_event_email_uniq'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(condition=models.Q(('device_hash', ''), _negated=True), fields=('event', 'device_hash'), name='community_voter_event_device_uniq'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gte', 1)), name='community_voting_credits_positive'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('max_votes_per_project__gte', 1)), name='community_max_votes_positive'),
        ),
    ]
