# Generated by Django 5.2.17 on 2026-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('events', '0004_alter_event_shrinkage_lambda'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('style', 'quadratic'), ('max_votes_per_project', 1), _connector='OR'), name='community_single_vote_limit_is_one'),
        ),
    ]
