# Generated by Django 5.2.17 on 2026-09-27 10:55

import django.db.models.deletion
import interop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_alter_event_shrinkage_lambda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=interop.models._new_wh_id, max_length=32)),
                ('url', models.URLField(max_length=1000)),
                ('secret', models.CharField(max_length=128)),
                ('event_types', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_endpoints_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='events.event')),
            ],
            options={
                'db_table': 'interop_webhook_endpoint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=interop.models._new_wd_id, max_length=32)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='events.event')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='interop.webhookendpoint')),
            ],
            options={
                'db_table': 'interop_webhook_delivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeParticipationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(default=interop.models._new_record_id, max_length=32)),
                ('kid', models.CharField(max_length=32)),
                ('record', models.JSONField()),
                ('signature', models.CharField(max_length=256)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_records', to='events.event')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_records_issued', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_records', to='events.eventrole')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_records_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interop_judge_participation_record',
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'record_id'), name='interop_record_id_per_event'), models.UniqueConstraint(fields=('event', 'judge'), name='interop_record_one_per_judge_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.UniqueConstraint(fields=('event', 'public_id'), name='interop_wh_unique_public_id'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='interop_wd_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'public_id'), name='interop_wd_unique_public_id'),
        ),
    ]
