# Generated by Django 5.2.17 on 2026-09-26 18:11

import django.db.models.deletion
import events.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('source_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('submissions_open_at', models.DateTimeField(blank=True, null=True)),
                ('submissions_close_at', models.DateTimeField()),
                ('judging_open_at', models.DateTimeField(blank=True, null=True)),
                ('judging_close_at', models.DateTimeField(blank=True, null=True)),
                ('voting_open_at', models.DateTimeField(blank=True, null=True)),
                ('voting_close_at', models.DateTimeField(blank=True, null=True)),
                ('max_team_size', models.PositiveSmallIntegerField(default=4)),
                ('reviews_per_project', models.PositiveSmallIntegerField(default=3)),
                ('judging_mode', models.CharField(choices=[('rubric', 'Rubric'), ('pairwise', 'Pairwise'), ('both', 'Both')], default='rubric', max_length=16)),
                ('ranking_method', models.CharField(choices=[('normalized', 'Normalized (judge offsets)'), ('raw', 'Raw mean'), ('pairwise', 'Pairwise (Bradley-Terry)')], default='normalized', max_length=16)),
                ('shrinkage_lambda', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('scoring_locked_at', models.DateTimeField(blank=True, null=True)),
                ('gallery_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=events.models._new_q_id, max_length=32)),
                ('prompt', models.CharField(max_length=300)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('url', 'URL'), ('choice', 'Choice'), ('yes_no', 'Yes / no')], default='short_text', max_length=16)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.event')),
            ],
            options={
                'db_table': 'events_custom_question',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=events.models._new_trk_id, max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('source_id', models.CharField(blank=True, max_length=40, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'db_table': 'events_track',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=events.models._new_prz_id, max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('value', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.track')),
            ],
            options={
                'db_table': 'events_prize',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('judge', 'Judge'), ('organizer', 'Organizer')], max_length=16)),
                ('public_id', models.CharField(max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=40, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_added', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_roles', to=settings.AUTH_USER_MODEL)),
                ('tracks', models.ManyToManyField(blank=True, related_name='judge_roles', to='events.track')),
            ],
            options={
                'db_table': 'events_event_role',
                'ordering': ['role', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('submissions_open_at__isnull', True), ('submissions_open_at__lt', models.F('submissions_close_at')), _connector='OR'), name='event_submissions_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('judging_open_at__isnull', True), ('judging_open_at__gte', models.F('submissions_close_at')), _connector='OR'), name='event_judging_after_submissions'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('judging_close_at__isnull', True), ('judging_open_at__isnull', True), ('judging_close_at__gt', models.F('judging_open_at')), _connector='OR'), name='event_judging_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('max_team_size__gte', 1), ('max_team_size__lte', 10)), name='event_max_team_size_range'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('reviews_per_project__gte', 1)), name='event_reviews_per_project_positive'),
        ),
        migrations.AddConstraint(
            model_name='customquestion',
            constraint=models.UniqueConstraint(fields=('event', 'public_id'), name='question_unique_public_id_per_event'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='track_unique_name_per_event'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'public_id'), name='track_unique_public_id_per_event'),
        ),
        migrations.AddConstraint(
            model_name='prize',
            constraint=models.UniqueConstraint(fields=('event', 'public_id'), name='prize_unique_public_id_per_event'),
        ),
        migrations.AddConstraint(
            model_name='eventrole',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='role_unique_per_event_user'),
        ),
        migrations.AddConstraint(
            model_name='eventrole',
            constraint=models.UniqueConstraint(fields=('event', 'public_id'), name='role_unique_public_id_per_event'),
        ),
    ]
