# Generated by Django 5.2.17 on 2026-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_prize_allocation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='shrinkage_lambda',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Shrinkage penalty λ; null = auto (5-fold CV, BUILD-SPEC 19).', max_digits=5, null=True),
        ),
    ]
