"""Accounts: the custom user (email login) and hashed bearer tokens."""
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils import timezone

from core.ids import new_public_id


def _new_usr_id() -> str:
    return new_public_id("usr")


class UserManager(BaseUserManager):
    """Email is the login identifier; there is no username field."""

    use_in_migrations = True

    def _create(self, email: str, password: str | None, **extra):
        if not email:
            raise ValueError("An email address is required.")
        email = self.normalize_email(email).lower()
        user = self.model(email=email, **extra)
        if password:
            user.set_password(password)
        else:
            user.set_unusable_password()
        user.save(using=self._db)
        return user

    def create_user(self, email: str, password: str | None = None, **extra):
        extra.setdefault("is_admin", False)
        extra.setdefault("is_host", False)
        return self._create(email, password, **extra)

    def create_superuser(self, email: str, password: str | None = None, **extra):
        extra["is_admin"] = True
        extra["is_host"] = True
        return self._create(email, password, **extra)

    def get_by_natural_key(self, username):
        return self.get(email=username)


class User(AbstractBaseUser):
    """A person. Roles per event live in events.EventRole, not here."""

    public_id = models.CharField(max_length=32, unique=True, default=_new_usr_id)
    email = models.EmailField(unique=True)
    display_name = models.CharField(max_length=80, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_host = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS: list[str] = []

    objects = UserManager()

    class Meta:
        db_table = "accounts_user"
        ordering = ["email"]

    def __str__(self) -> str:
        return self.display_name or self.email

    def get_full_name(self) -> str:
        return self.display_name

    def get_short_name(self) -> str:
        return (self.display_name or self.email).split(" ")[0]

    @property
    def is_staff(self) -> bool:
        """Django admin is never mounted; the flag stays False to avoid confusion."""
        return False


class ApiToken(models.Model):
    """A hashed bearer token. The plaintext is shown once at creation."""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="api_tokens")
    name = models.CharField(max_length=80)
    prefix = models.CharField(max_length=16, db_index=True)
    key_hash = models.CharField(max_length=64, unique=True)
    last_used_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)
    is_demo = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "accounts_api_token"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.name} ({self.prefix}…)"

    @property
    def is_valid(self) -> bool:
        return self.revoked_at is None


class PasswordResetToken(models.Model):
    """Offline one-time reset link generated by an admin (BUILD-SEC 16)."""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reset_tokens")
    token_hash = models.CharField(max_length=64, unique=True)
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name="reset_tokens_created")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "accounts_password_reset_token"
        ordering = ["-created_at"]
