# Generated by Django 5.2.17 on 2026-09-26 18:11

import django.db.models.deletion
import judging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('min_score', models.PositiveSmallIntegerField(default=1)),
                ('max_score', models.PositiveSmallIntegerField(default=5)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'judging_criterion',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic'), ('import', 'Import')], max_length=16)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_batches_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_batches', to='events.event')),
            ],
            options={
                'db_table': 'judging_assignment_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=judging.models._new_asg_id, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.eventrole')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='judging.assignmentbatch')),
            ],
            options={
                'db_table': 'judging_assignment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='events.eventrole')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_left', to='projects.project')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_right', to='projects.project')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_won', to='projects.project')),
            ],
            options={
                'db_table': 'judging_comparison',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('declared_by_judge', 'Declared by judge'), ('organizer', 'Organizer')], default='organizer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='events.eventrole')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='teams.team')),
            ],
            options={
                'db_table': 'judging_conflict',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JudgeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=judging.models.new_judge_invite_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_invites_accepted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_invites_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_invites', to='events.event')),
                ('tracks', models.ManyToManyField(blank=True, related_name='judge_invites', to='events.track')),
            ],
            options={
                'db_table': 'judging_judge_invite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=judging.models._new_rev_id, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=16)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rubric_version', models.PositiveIntegerField(default=1)),
                ('project_revision', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('live', 'Live'), ('import', 'Import')], default='live', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='judging.assignment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.eventrole')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
            ],
            options={
                'db_table': 'judging_review',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.criterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.review')),
            ],
            options={
                'db_table': 'judging_criterion_score',
                'ordering': ['criterion_id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_exclusions_created', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion', to='judging.review')),
            ],
            options={
                'db_table': 'judging_review_exclusion',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='events.event')),
            ],
            options={
                'db_table': 'judging_rubric',
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='judging.rubric'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('judge', 'project'), name='assignment_unique_judge_project'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('event', 'public_id'), name='assignment_unique_public_id_per_event'),
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.CheckConstraint(condition=models.Q(('left', models.F('right')), _negated=True), name='comparison_distinct_projects'),
        ),
        migrations.AddConstraint(
            model_name='conflict',
            constraint=models.UniqueConstraint(fields=('judge', 'team'), name='conflict_unique_judge_team'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('event', 'public_id'), name='review_unique_public_id_per_event'),
        ),
        migrations.AddConstraint(
            model_name='criterionscore',
            constraint=models.UniqueConstraint(fields=('review', 'criterion'), name='score_unique_per_review'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'key'), name='criterion_unique_key_per_rubric'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='criterion_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', models.F('min_score'))), name='criterion_max_above_min'),
        ),
    ]
