# Generated by Django 5.2.17 on 2026-09-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentbatch',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic'), ('import', 'Import'), ('rebalance', 'Rebalance')], max_length=16),
        ),
    ]
